/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "inverse-primary": "#ffb3ad",
        "surface-tint": "#c0011b",
        "surface-bright": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        outline: "#916f6c",
        "primary-container": "#d71e28",
        "tertiary-fixed-dim": "#cfc6b3",
        "inverse-surface": "#303030",
        "on-primary-container": "#ffeeec",
        "on-tertiary-container": "#faf0dc",
        tertiary: "#5b5546",
        "on-primary-fixed": "#410003",
        "on-primary": "#ffffff",
        "outline-variant": "#e6bdb9",
        primary: "#af0017",
        "primary-fixed-dim": "#ffb3ad",
        error: "#ba1a1a",
        "primary-fixed": "#ffdad6",
        "on-secondary-container": "#765600",
        "surface-dim": "#dcd9d9",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#5c4300",
        "surface-variant": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1c1c",
        "on-secondary-fixed": "#261900",
        "surface-container-highest": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#201b0f",
        "tertiary-container": "#746d5d",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "secondary-container": "#fdce6d",
        "on-primary-fixed-variant": "#930011",
        "secondary-fixed": "#ffdea1",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#4c4638",
        surface: "#fcf9f8",
        "on-surface-variant": "#5c3f3d",
        background: "#fcf9f8",
        "surface-container": "#f0eded",
        "secondary-fixed-dim": "#eec061",
        secondary: "#7a5900",
        "tertiary-fixed": "#ebe2ce",
        "on-surface": "#1b1c1c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "sidebar-width": "260px",
        "margin-desktop": "32px",
        "container-max-width": "1440px",
        gutter: "24px",
        unit: "4px",
      },
      fontFamily: {
        "display-lg": ['"Source Serif 4"'],
        caption: ["Work Sans"],
        "headline-lg": ['"Source Serif 4"'],
        "title-lg": ["Work Sans"],
        "headline-md": ['"Source Serif 4"'],
        "body-md": ["Work Sans"],
        "label-md": ["Work Sans"],
        "body-lg": ["Work Sans"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
    container: {
      screens: {
        DEFAULT: "1440px",
      },
    },
  },
  plugins: [],
}
